name: NuGet Publish

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore src/Blazor.Heroicons/Blazor.Heroicons.csproj
      - name: Build
        run: dotnet build src/Blazor.Heroicons/Blazor.Heroicons.csproj --no-restore --configuration Release
      - name: Pack
        run: dotnet pack src/Blazor.Heroicons/Blazor.Heroicons.csproj --no-build --configuration Release -o .
      - name: Publish package to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
